name: Testing

on:
  pull_request:
    branches: [ test ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Additional dependencies
      run: pip install pytest

    - name: Run tests
      run: python test.py

    - name: Create pull request to merge changes to master
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Merge test branch changes to master"
        body: |
          This pull request is automatically created after successful completion of test cases.
        branch: main
